# Generated by Django 6.0.7 on 2026-07-30 15:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0069_log_entry_jsonfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("embed", 3),
                            ("table", 4),
                            ("callout", 6),
                            ("bullet_points", 7),
                            ("section", 9),
                            ("raw_html", 10),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {"required": False}),
                            3: ("wagtail.embeds.blocks.EmbedBlock", (), {"required": False}),
                            4: (
                                "wagtail.contrib.table_block.blocks.TableBlock",
                                (),
                                {"required": False},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            6: ("wagtail.blocks.StructBlock", [[("title", 5), ("body", 1)]], {}),
                            7: ("wagtail.blocks.ListBlock", (0,), {}),
                            8: (
                                "wagtail.blocks.StreamBlock",
                                [[("paragraph", 1), ("callout", 6)]],
                                {"required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("content", 8)]],
                                {},
                            ),
                            10: ("wagtail.blocks.RawHTMLBlock", (), {"required": False}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
