# Generated by Django 6.0.7 on 2026-09-21 10:12

import django.db.models.deletion
from django.db import migrations, models

import wagtail_markdown_agents.panels


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_page_rendering_fixtures"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkdownArticlePage",
            fields=[
                (
                    "articlepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="testapp.articlepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail_markdown_agents.panels.AgentMarkdownPanelMixin, "testapp.articlepage"),
        ),
    ]
