# Generated by Django 6.0.8 on 2026-09-25 13:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wtrx", "0002_integrationsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationsettings",
            name="integrations",
            field=wagtail.fields.StreamField(
                [("actionkit", 2), ("actblue", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.BooleanBlock", (), {"default": True, "required": False}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: ("wagtail.blocks.StructBlock", [[("enabled", 0), ("hostname", 1)]], {}),
                    3: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("enabled", 0), ("base_url", 3), ("suggested_amounts", 1)]],
                        {},
                    ),
                },
            ),
        ),
    ]
