# Generated by Django 6.0.7 on 2026-09-14 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_markdown_agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("site_id", models.PositiveIntegerField(unique=True)),
                ("version", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ExportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("page_id", models.PositiveIntegerField(null=True)),
                ("logical_path", models.CharField(max_length=1024)),
                ("storage_alias", models.CharField(blank=True, max_length=255)),
                ("storage_fingerprint", models.CharField(max_length=64)),
                ("requested_key", models.CharField(max_length=1024)),
                ("storage_key", models.CharField(max_length=1024)),
                ("cleanup_pending", models.BooleanField(default=False)),
                ("notify_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wagtail_markdown_agents.exportscope",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("page_id", models.PositiveIntegerField(null=True)),
                ("logical_path", models.CharField(max_length=1024, unique=True)),
                ("source_state", models.CharField(max_length=64)),
                ("dependency_state", models.CharField(blank=True, default="", max_length=64)),
                ("published_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifact",
                        to="wagtail_markdown_agents.exportfile",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wagtail_markdown_agents.exportscope",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "page_id"), name="agentmd_scope_page_unique"
                    )
                ],
            },
        ),
    ]
