# Generated by Django 6.0.7 on 2026-09-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_markdown_agents", "0002_export_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportscope",
            name="content_version",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
