# Generated by Django 6.0.7 on 2026-09-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_markdown_agents", "0003_content_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportscope",
            name="manifest_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
